export enum Subject {
    BIOLOGY_AND_ECOLOGY = "Біологія і екологія",
    INTRODUCTION_TO_SPECIALTY = "Вступ до спеціальності",
    CIVIC_EDUCATION = "Громадянська освіта",
    ADDITIONAL_MATH_SECTIONS = "Додаткові розділи математики",
    ECOLOGY = "Екологія",
    FOREIGN_LANGUAGE = "Іноземна мова",
    INFORMATICS = "Інформатика",
    UKRAINIAN_HISTORY = "Історія України",
    CULTUROLOGY = "Культурологія",
    LINEAR_ALGEBRA_AND_ANALYTICAL_GEOMETRY = "Лінійна алгебра та аналітична геометрія",
    MATHEMATICS = "Математика",
    MATHEMATICAL_ANALYSIS = "Математичний аналіз",
    ART = "Мистецтво",
    BASICS_OF_LEGAL_STUDIES = "Основи правознавства",
    UKRAINIAN_LITERATURE = "Українська література",
    UKRAINIAN_LANGUAGE = "Українська мова",
    PHYSICS_ELECTRICS = "Фізика (Електрика)",
    PHYSICS_AND_ASTRONOMY = "Фізика і астрономія",
    PHYSICAL_EDUCATION = "Фізична культура",
    EXCEL_SCHOOL = "Школа Excel",
    NONE = "-"
}